apiVersion: gitlab.organization.io/v1alpha1
kind: xTeamEnvironment
metadata:
  name: test
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      type: dynamic
  projectDescription: A short description
  projectName: test-repo
  teamName: test-team
  visibilityLevel: internal
  environmentVariables:
    - key: API_URL
      masked: false
      protected: true
      value: https://api.example.com
    - key: DEBUG
      masked: false
      protected: false
      value: "true"
    - key: LOG_LEVEL
      masked: false
      protected: false
      value: info
